const userResourceOptions = {
  navigation: "Users Management",
  editProperties: [
    "user_type",
    "name",
    "last_name",
    "email",
    "password",
    "profile_picture",
    "bio",
    "is_verified",
    "role",
  ],
  filterProperties: [
    "user_type",
    "name",
    "last_name",
    "email",
    "password",
    "profile_picture",
    "bio",
    "is_verified",
    "role",
  ],
  listProperties: [
    "user_type",
    "name",
    "last_name",
    "email",
    "password",
    "profile_picture",
    "bio",
    "is_verified",
    "role",
    "createdAt",
  ],
  showProperties: [
    "id",
    "user_type",
    "name",
    "last_name",
    "email",
    "profile_picture",
    "bio",
    "is_verified",
    "role",
    "createdAt",
    "updatedAt",
  ],
};

module.exports = { userResourceOptions };
